### ISSUE TITLE
Add test phase in Docker

### ISSUE THREAD

**Issue by pipa** [la5ta/tally-web#1]
Make the testing phase work! 

Take a look at the [Dockerfile](https://github.com/la5ta/tally-web/blob/master/Dockerfile#L28)

**Comment by JdgaleTorre** [comment]
I already add the test phase on the docker, but I have one question:
The step of install package of production, with these steps the `yarn build && yarn test` throw an error because there're errors on /prod_node_modules/.
And didn't find how to exclude this directory.

**Comment by pipa** [comment]
Fixed in #11
